name: 'Store Upload Action'
description: 'Generates goldens, reframes screenshots with texts/devices, builds AAB/IPA, and publishes to stores'
inputs:
  screenshot_background:
    description: 'Screenshot background color'
    required: true
    default: '#009688'
  screenshot_ellipse:
    description: 'Screenshot ellipse color'
    required: true
    default: '#3F51B5'
  screenshot_outline:
    description: 'Screenshot outline color'
    required: true
    default: '#009688'
  apple_key_id:
    description: 'Apple Key ID'
    required: true
  apple_p8_folder:
    description: 'Apple .p8 private key folder'
    required: true
  apple_issuer_id:
    description: 'Apple Issuer UUID'
    required: true
    default: '00000000-0000-0000-0000-000000000000'
  google_service_account_path:
    description: 'Google Play service account path'
    required: true
  google_track:
    description: 'Google Play track'
    required: true
    default: 'production'

runs:
  using: 'composite'
  steps:
    - name: Run tests and generate goldens
      shell: bash
      run: flutter test --update-goldens

    - name: Generate HTML page with screenshots
      if: inputs.generate_html == 'true'
      shell: bash
      run: |
          version=$(git describe --tags --always --dirty)
          appName=$(awk -F'"' '/android:label=/{print $(NF-1)}' android/app/src/main/AndroidManifest.xml)
          cat <<EOF >metadata/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8" />
              <title>$appName @ $version</title>
            </head>
            <body>
              <p>Built on $(TZ=America/Los_Angeles date) — $version</p>
              <table>
                <thead>
                <tr>
                  <th>device</th>
          EOF
            for f in en-US/images/phoneScreenshots/*; do
              name=$(basename "$f" | sed s/.png//)
              cat <<EOF >>metadata/index.html
                  <th>$name</th>
          EOF
          
            done
            cat <<EOF >>metadata/index.html
                </tr>
                </thead>
                <tbody>
          EOF
          
            for d in en-US/images/*; do
              device=$(basename "$d")
              cat <<EOF >>metadata/index.html
                <tr>
                  <th>
                    <p>$device</p>
                  </th>
          EOF
              for img in "$d"/*.png; do
                cat <<EOF >>metadata/index.html
                  <td>
                    <a href="$img"><img src="$img" style="width: 300px; text-align: center"/></a>
                  </td>
          EOF
              done
              cat <<EOF >>metadata/index.html
                </tr>
          EOF
            done
            cat <<EOF >>metadata/index.html
              </table>
            </body>
          </html>
          EOF

    - name: Set up Python
      shell: bash
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/scripts/requirements.txt

    - name: Reframe screenshots
      shell: bash
      run: |
        for dev in '${{ github.action_path }}/assets/'*.png; do
          folder="metadata/en-US/images/$(basename "$dev" | sed s/.png//)"
          for screenshot in "${folder}/"*.png; do
            .venv/bin/python '${{ github.action_path }}/scripts/reframe_screenshot.py' \
              --font '${{ github.action_path }}/assets/'*.ttf \
              --background '${{ inputs.screenshot_background }}' \
              --ellipse '${{ inputs.screenshot_ellipse }}' \
              --outline '${{ inputs.screenshot_outline }}' \
              --screenshot "$screenshot" \
              --device "$dev" \
              --text "$(cat metadata/en-US/images/$(basename "$f" | sed s/.png/.txt/))"
          done
        done

    - name: Auto-detect package_name and bundle_id
      id: detect-ids
      shell: bash
      run: |
        echo "PACKAGE_NAME=$(awk -F'"' '/\<applicationId\>/{print $(NF-1); exit}' android/app/build.gradle*)" >>$GITHUB_OUTPUT
        echo "BUNDLE_ID=$(awk '/\<PRODUCT_BUNDLE_IDENTIFIER\>/{gsub(/;/, "", $3); print $3; exit}' ios/Runner.xcodeproj/project.pbxproj)" >>$GITHUB_OUTPUT

    - name: Prepare credentials and publish
      shell: bash
      run: |
        .venv/bin/python ${{ github.action_path }}/scripts/publish.py \
          --package_name          "${{ steps.detect-ids.outputs.package_name }}" \
          --service_account_json  "${{ inputs.google_service_account_path }}" \
          --track                 "${{ inputs.google_track }}" \
          --bundle_id             "${{ steps.detect-ids.outputs.bundle_id }}" \
          --key_id                "${{ inputs.apple_key_id }}" \
          --p8_folder             "${{ inputs.apple_p8_folder }}" \
          --issuer_id             "${{ inputs.apple_issuer_id }}"
